- src/main/resources/org/jenkinsci/plugins/credentialsbinding/impl/BindingStep/help.html
> Inlining help

- src/test/java/org/jenkinsci/plugins/credentialsbinding/impl/UsernamePasswordMultiBindingTest.java
Without this fix I get a test failure:
```
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 16.103 sec <<< FAILURE! - in org.jenkinsci.plugins.credentialsbinding.impl.UsernamePasswordMultiBindingTest
basics(org.jenkinsci.plugins.credentialsbinding.impl.UsernamePasswordMultiBindingTest)  Time elapsed: 16.102 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[bob/s3cr3t]> but was:<[/]>
at org.junit.Assert.assertEquals(Assert.java:115)
at org.junit.Assert.assertEquals(Assert.java:144)
at org.jenkinsci.plugins.credentialsbinding.impl.UsernamePasswordMultiBindingTest.basics(UsernamePasswordMultiBindingTest.java:67)
```
> Fixed tests on Windows

- pom.xml
- src/test/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStepTest.java
- src/test/java/org/jenkinsci/plugins/credentialsbinding/impl/UsernamePasswordBindingTest.java
- src/test/java/org/jenkinsci/plugins/credentialsbinding/impl/UsernamePasswordMultiBindingTest.java
added a test case for [JENKINS-30326](https://issues.jenkins-ci.org/browse/JENKINS-30326) and up the dependency to pull in the fix.
@reviewbybees -esp @jglick
> Jenkins 30326

- src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/ZipFileBinding.java
> Fix resource leak identified by eclipse

- src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/FileBinding.java
- src/main/resources/org/jenkinsci/plugins/credentialsbinding/impl/BindingStep/help.html
- src/test/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStepTest.java
[JENKINS-32943](https://issues.jenkins-ci.org/browse/JENKINS-32943)
Matches https://github.com/jenkinsci/docker-workflow-plugin/pull/33.
@reviewbybees
> [JENKINS-32943] Use a standardized temporary directory for secretFiles

- src/main/resources/org/jenkinsci/plugins/credentialsbinding/MultiBinding/config.jelly
- src/main/resources/org/jenkinsci/plugins/credentialsbinding/impl/BindingStep/config.jelly
- src/main/resources/org/jenkinsci/plugins/credentialsbinding/impl/SecretBuildWrapper/config.jelly
[JENKINS-27387](https://issues.jenkins-ci.org/browse/JENKINS-27387)
@reviewbybees esp. @stephenc who is responsible for the weirdness in `select.jelly`.
> [JENKINS-27387] NPE from Snippetizer

- pom.xml
- src/main/java/org/jenkinsci/plugins/credentialsbinding/Binding.java
- src/main/java/org/jenkinsci/plugins/credentialsbinding/MultiBinding.java
- src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStep.java
- src/main/resources/index.jelly
- Migrate to 2.9 parent pom
- Findbugs issues
- Injected test fix
@reviewbybees
> [JENKINS-35095] Findbugs issues. Migrate to 2.9 parent pom.

- src/main/resources/org/jenkinsci/plugins/credentialsbinding/impl/SecretBuildWrapper/config.jelly
[JENKINS-35490](https://issues.jenkins-ci.org/browse/JENKINS-35490)
@reviewbybees
> [FIXED JENKINS-35490] Ensure the expressionAllowed variable is captured for the hetero-add

- pom.xml
- src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/SecretBuildWrapper.java
Also bumped version of parent POM
https://issues.jenkins-ci.org/browse/JENKINS-37541
@reviewbybees
> [JENKINS-37541] Protect ourselves against deserialization with null binding

- src/test/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStepTest.java
> Minor test cleanup

- pom.xml
- src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStep.java
- src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/FileBinding.java
- src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/StringBinding.java
- src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/UsernamePasswordBinding.java
- src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/UsernamePasswordMultiBinding.java
- src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/ZipFileBinding.java
- src/main/resources/org/jenkinsci/plugins/credentialsbinding/impl/BindingStep/help.html
- src/test/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStepTest.java
- src/test/java/org/jenkinsci/plugins/credentialsbinding/impl/UsernamePasswordBindingTest.java
- src/test/java/org/jenkinsci/plugins/credentialsbinding/impl/ZipFileBindingTest.java
> Adding symbols to binding types for easier usage

- pom.xml
- src/test/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStepTest.java
[JENKINS-41752](https://issues.jenkins-ci.org/browse/JENKINS-41752)
- Force the creation of the user, to avoid depending on new User.ALLOW_USER_CREATION_VIA_URL property.
- Update test dependencies for instance to start.
@reviewbybees @stephenc
> [JENKINS-41752] Fix PCT for 2.32.2

- src/main/java/org/jenkinsci/plugins/credentialsbinding/MultiBinding.java
- src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStep.java
- src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/SecretBuildWrapper.java
- src/test/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStepTest.java
- src/test/java/org/jenkinsci/plugins/credentialsbinding/impl/SecretBuildWrapperTest.java
[JENKINS-41760](https://issues.jenkins-ci.org/browse/JENKINS-41760)
#35 but with test coverage.
@reviewbybees
> [JENKINS-41760] Suppress masking of blank secrets

- src/main/java/org/jenkinsci/plugins/credentialsbinding/MultiBinding.java
- src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStep.java
- src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/SecretBuildWrapper.java
Fix for [JIRA](https://issues.jenkins-ci.org/browse/JENKINS-41760)
> [JENKINS-41760] Broken output when empty secret

- pom.xml
[JENKINS-48118](https://issues.jenkins-ci.org/browse/JENKINS-48118)
- Add direct dependency with `workflow-support` in scope test.
@reviewbybees
> [JENKINS-48118] Missing dependency in scope test

- src/main/resources/org/jenkinsci/plugins/credentialsbinding/impl/BindingStep/help.html
[JENKINS-50242](https://issues.jenkins-ci.org/browse/JENKINS-50242) but a general review of the text and better guidance.
@reviewbybees
> [JENKINS-50242] Improved help text to correct a misunderstanding

- src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStep.java
- src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/SecretBuildWrapper.java
As in https://github.com/jenkinsci/jenkins/pull/3703.
> Forgot to override LineTransformationOutputStream.flush

- .mvn/extensions.xml
- .mvn/maven.config
- Jenkinsfile
- pom.xml
- src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStep.java
Downstream of https://github.com/jenkinsci/workflow-step-api-plugin/pull/38.
> Using GeneralNonBlockingStepExecution

- pom.xml
- src/main/java/org/jenkinsci/plugins/credentialsbinding/MultiBinding.java
- src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStep.java
- src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/CertificateMultiBinding.java
- src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/SSHUserPrivateKeyBinding.java
- src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/UsernamePasswordMultiBinding.java
- src/main/resources/org/jenkinsci/plugins/credentialsbinding/impl/BindingStep/config.jelly
- src/main/resources/org/jenkinsci/plugins/credentialsbinding/impl/BindingStep/config.properties
- src/main/resources/org/jenkinsci/plugins/credentialsbinding/impl/BindingStep/help.html
- src/test/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStepTest.java
[JENKINS-42950](https://issues.jenkins-ci.org/browse/JENKINS-42950)
> [JENKINS-42950] Making users more aware of behavior

- README.md
Amends #110.
Origin branch because edited in GH. Please delete on merge.
> Improve interpolation documentation and changelog references

- src/main/java/org/jenkinsci/plugins/credentialsbinding/MultiBinding.java
- src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStep.java
- src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/SecretBuildWrapper.java
- src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/UsernamePasswordMultiBinding.java
- src/test/java/org/jenkinsci/plugins/credentialsbinding/impl/SSHUserPrivateKeyTest.java
- src/test/java/org/jenkinsci/plugins/credentialsbinding/impl/UsernamePasswordMultiBindingTest.java
Carry of #44 
Fixes [JENKINS-44860](https://issues.jenkins-ci.org/browse/JENKINS-44860)
> [JENKINS-44860] Disable masking of usernames

- src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStep.java
- src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/SecretBuildWrapper.java
Picks up https://github.com/jenkinsci/jenkins/pull/3959.
> Use `LineTransformationOutputStream.Delegating`

- Jenkinsfile
- pom.xml
Supersedes #173 & #174; picks up https://github.com/jenkinsci/bom/pull/970, cleaning up after #169.
> Update POM & BOM, test on Java 17

- pom.xml
- src/test/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStepTest.java
Downstream of https://github.com/jenkinsci/jenkins-test-harness/pull/428.
> [JENKINS-26398] Use standard `JenkinsRule.createSlave`

- Jenkinsfile
- pom.xml
- src/main/java/org/jenkinsci/plugins/credentialsbinding/masking/SecretPatterns.java
> Update to 2.361.x

- src/main/java/org/jenkinsci/plugins/credentialsbinding/masking/SecretPatterns.java
This applies the security improvement delivered in https://github.com/jenkinsci/credentials-binding-plugin/releases/tag/523.525.vb_72269281873 to the default branch.
This PR can be squash-merged, rebase-merged, etc., doesn't matter, as it does not merge in the specific commit released in 523.525.vb_72269281873
**IMPORTANT**: To prevent accidental CD releases without this improvement, I have made the default branch read-only. Happy to undo that once this is ready to be merged.
> [SECURITY-3075] Mask passwords even when downstream plugins are unpatched

- src/main/java/org/jenkinsci/plugins/credentialsbinding/masking/SecretPatterns.java
Helpful for tests in https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/323.
> Legible `MaskingOutputStream.toString`
