pom.xml, src/test/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStepTest.java
[JENKINS-27631](https://issues.jenkins-ci.org/browse/JENKINS-27631)
I lay awake in bed wondering whether the contextual `EnvVars` got stored somewhere unsafe. Turns out it does, though only temporarily. This PR just makes the test coverage more interesting.
@reviewbybees
=> [JENKINS-27631] Stronger tests

src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/FileBinding.java
[JENKINS-29255](https://issues.jenkins-ci.org/browse/JENKINS-29255)
=> [FIXED JENKINS-29255] Restricting secret file visibility to avoid "WARNING: UNPROTECTED PRIVATE KEY FILE!" when using as ssh key

src/main/resources/org/jenkinsci/plugins/credentialsbinding/impl/BindingStep/help.html
You can use the secret text credentials with the pipeline step.  This should be added to the documentation.  I'm copied this from [#347](https://github.com/jenkins-infra/jenkins.io/pull/347) since that file is generated from the help.html from this plugin.
cc @nzakas to ensure the info is still accurate
=> Mention secret text as part of pipeline option.

src/main/java/org/jenkinsci/plugins/credentialsbinding/MultiBinding.java, src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStep.java, src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/SecretBuildWrapper.java, src/test/java/org/jenkinsci/plugins/credentialsbinding/impl/SecretBuildWrapperTest.java
[JENKINS-24805](https://issues.jenkins-ci.org/browse/JENKINS-24805)
This still needs tests - I just want to make sure the approach is right.
cc @reviewbybees esp @jglick
=> [JENKINS-24805] Start masking secrets in freestyle logs.

src/main/java/org/jenkinsci/plugins/credentialsbinding/MultiBinding.java, src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStep.java, src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/SecretBuildWrapper.java, src/test/java/org/jenkinsci/plugins/credentialsbinding/impl/SecretBuildWrapperTest.java
This is on top of #28. Relevant diff to start at https://github.com/jenkinsci/credentials-binding-plugin/pull/29/commits/9a760d413e501e66ec21bd124dc6bd71e814900b
cc @reviewbybees esp @jglick
=> Fix a bug with masking of secrets containing other secrets as substrings.

pom.xml
https://wiki.jenkins-ci.org/display/JENKINS/Usage+Statistics+Privacy+Advisory+2016-03-30:
It seems to also affect tests execution when jenkins.version=1.642.3, and becomes
annoying when stuck behind a corporate HTTP proxy, because each test execution then
hangs until the TCP connection attempt aborts. Bumping to 1.642.4 is enough to make
the tests fast again.
Here is an example stack captured when the external ressource HTTP request happens
during a test execution (with 1.642.3):
```
"Executing emptySecretsList(org.jenkinsci.plugins.credentialsbinding.impl.SecretBuildWrapperTest)" prio=10 tid=0x00007f855800a800 nid=0x7f69 runnable [0x00007f85622fa000]
java.lang.Thread.State: RUNNABLE
at java.net.PlainSocketImpl.socketConnect(Native Method)
at …
```
=> use jenkins 1.642.4, to avoid requests to usage.jenkins.io from automated tests

src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/AbstractOnDiskBinding.java, src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/FileBinding.java, src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/ZipFileBinding.java
Following jglick's suggestion in #22, I will make a PR for a Docker client certificate Binding implementation to the docker-commons-plugin. To write it without copy/pasting too much code from FileBinding, I would like to introduce an abstract class for this kind of on-disk credentials binding implementation, which would take care of the temporary directory, but would not be specific to FileCredentials.
**EDIT:** posted the PR for docker-commons: jenkinsci/docker-commons-plugin#54
=> Ease writing of new on-disk Binding implementations

pom.xml, src/main/java/org/jenkinsci/plugins/credentialsbinding/Binding.java, src/main/java/org/jenkinsci/plugins/credentialsbinding/BindingDescriptor.java, src/main/java/org/jenkinsci/plugins/credentialsbinding/MultiBinding.java, src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStep.java, src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/FileBinding.java, src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/StringBinding.java, src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/UsernamePasswordBinding.java, src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/UsernamePasswordMultiBinding.java, src/test/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStepTest.java
[JENKINS-42999](https://issues.jenkins-ci.org/browse/JENKINS-42999)
Not all bindings require a workspace, and those that don't should be
able to be used in `withCredentials` outside of a `node` block. This
adds `BindingDescriptor.getRequiredContext()`, defaulting to the four
contexts that were previously required by `BindingStep`, but allowing
override. `BindingStep` will now throw a
`MissingContextVariableException` if any of the `MultiBinding`s used
have a required context that cannot be satisfied, as well as the
normal potential `MissingContextVariableException` for `BindingStep.DescriptorImpl.getRequiredContext()`.
In addition, bumped `workflow-step-api` to 2.9 and moved `BindingStep`
and friends to non-deprecated code paths while I was here.
cc @reviewbybees esp @jglick @stephenc …
=> [FIXED JENKINS-42999] Allow bindings to specify their required context

src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/AbstractOnDiskBinding.java, src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/FileBinding.java, src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/UnbindableDir.java, src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/ZipFileBinding.java
This PR is the successor of #25 (which was merged and then rolled-back, and thus can't be updated anymore). The goal is still to ease writing new credentials binding implementations which write to temp files without copy/pasting what exists already in FileBinder.
The code from #25 was reviewed already by @jglick, and it was fine, expect it was specific to writing Binding implementation, and was not supporting MultiBinding at all. Meaning it wasn't helping in cases like the SSH key binding proposed in #18 for instance.
This new PR includes two commits:
-	83ba9e2 are the changes already reviewed in PR #25, simply rebased on master
-	8c50bd3 is a refactoring to make some utility code also available to MultiBinding implementations. The AbstractOnDiskBinding API is unchanged (meaning …
=> Ease writing of new on-disk Binding implementations (take 2)

src/test/resources/org/jenkinsci/plugins/credentialsbinding/impl/CertificateMultiBindingTest/basicsPipeline-step1.sh
The `stat` CLI is appararently different on mac than it is on linux
=> Fix CertificateMultiBindingTest on mac

src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/SecretBuildWrapper.java
A fix for https://issues.jenkins-ci.org/browse/JENKINS-43199
=> Close logger to avoid file descriptor leaks

src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/SecretBuildWrapper.java, src/test/java/org/jenkinsci/plugins/credentialsbinding/impl/BuildWrapperOrderCredentialsBindingTest.java
- so the credentials-binding plugin is executed at the beginning of the
BuildWrapper phase. Otherwise it is executed too late, eg. when using
the pre-release build steps of the release-plugin and no credentials
are injected beforehand.
fixes [JENKINS-37871](https://issues.jenkins-ci.org/browse/JENKINS-37871)
=> [JENKINS-37871] Add ordinal 100 to Extension annotation

src/main/java/org/jenkinsci/plugins/credentialsbinding/MultiBinding.java
Jenkins Blue Ocean only shows the exception message if something goes wrong. The stacktrace is only available if users explicitly switch back to the "old" log viewer. Therefore, only providing the credentials ID as CredentialNotFoundException message, makes it hard for Blue Ocean users to get a grasp of the problem.
=> [JENKINS-49535] Improve error message when credentials entry is not found

src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/CredentialNotFoundException.java, src/test/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStepTest.java
Amends cb9191d0d201792477c196aa20d876e5eec33694 since we do not want to print a stack trace in the case of a simple user error (mistyped or otherwise missing `credentialsId`).
I was reluctant to just discard the special exception type, in case some scripts were `catch`ing it.
Saw in a build run by @Vlatombe.
=> Suppress stack trace from CredentialNotFoundException

src/test/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStepTest.java
Noticed a flake on Windows in a build of #55 which I thought might have been due to a race condition in `waitForCompletion` vs. logs:
```
Expected: a string containing "Required context class hudson.FilePath is missing"
but: was "Started
[Pipeline] withCredentials
[Pipeline] // withCredentials
[Pipeline] End of Pipeline
"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at org.jvnet.hudson.test.JenkinsRule.assertLogContains(JenkinsRule.java:1261)
at org.jenkinsci.plugins.credentialsbinding.impl.BindingStepTest$6.evaluate(BindingStepTest.java:225)
```
Evidently the build failed as expected but at the time of the assertion lacked the expected failure text.
=> Trying to avoid a test flake

src/main/java/org/jenkinsci/plugins/credentialsbinding/masking/AlmquistShellSecretPatternFactory.java, src/main/resources/org/jenkinsci/plugins/credentialsbinding/impl/BindingStep/help.html, src/test/java/org/jenkinsci/plugins/credentialsbinding/masking/AlmquistShellSecretPatternFactoryTest.java
Almquist shell is the default one for Alpine. The escape schema is a bit special compared to the other.
```
pwd="pass'word"
set -x
echo $pwd
```
outputs
`+ echo 'pass'"'"'word'`
You can reproduce those commands on `jenkinsci/jnlp-slave:alpine` default shell.
Unit tests added.
For the review information: `'` is escaped as `'"'"'`, `''` as `'"''"'`, `'''` as `'"'''"'`
@jvz
=> Add support for Almquist shell in masking

src/main/resources/org/jenkinsci/plugins/credentialsbinding/Binding/help-variable.html, src/main/resources/org/jenkinsci/plugins/credentialsbinding/impl/BindingStep/config.properties, src/main/resources/org/jenkinsci/plugins/credentialsbinding/impl/CertificateMultiBinding/help-keystoreVariable.html, src/main/resources/org/jenkinsci/plugins/credentialsbinding/impl/SSHUserPrivateKeyBinding/help-keyFileVariable.html
There has been some uncertainty or confusion about whether multi-line secrets are expected to be masked. These types of secrets include things like SSH private key and various types of certificates. This PR adds a sentence in a few places to clarify that multi-line secrets are not masked.
=> Add some documentation about not masking multi-line secrets.

README.md, src/main/resources/org/jenkinsci/plugins/credentialsbinding/impl/CertificateMultiBinding/help.html, src/main/resources/org/jenkinsci/plugins/credentialsbinding/impl/FileBinding/help.html, src/main/resources/org/jenkinsci/plugins/credentialsbinding/impl/SSHUserPrivateKeyBinding/help.html, src/main/resources/org/jenkinsci/plugins/credentialsbinding/impl/StringBinding/help.html, src/main/resources/org/jenkinsci/plugins/credentialsbinding/impl/UsernamePasswordBinding/help.html, src/main/resources/org/jenkinsci/plugins/credentialsbinding/impl/UsernamePasswordMultiBinding/help.html, src/main/resources/org/jenkinsci/plugins/credentialsbinding/impl/ZipFileBinding/help.html
I was looking at https://plugins.jenkins.io/credentials-binding/ and noticed that the docs still use the term 'slave', so we should update them.
=> Replace 'slave' with 'agent' in README and help text

README.md, src/main/resources/org/jenkinsci/plugins/credentialsbinding/impl/BindingStep/help.html
Increase the documented visibility of the recommendation to use single quotes whenever possible.
=> Highlight importance of using single-quotes.

pom.xml, src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStep.java, src/test/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStepTest.java
[JENKINS-63254](https://issues.jenkins-ci.org/browse/JENKINS-63254)
PoC version 2 for groovy string interpolation interception.
Relies on changes to `EnvironmentExpander`. Unlike version 1, does not require any changes to core.
Requires: https://github.com/jenkinsci/workflow-step-api-plugin/pull/57
Upstream: https://github.com/jenkinsci/workflow-cps-plugin/pull/370
TODO:
~- Add unit test(s)~
CC @dwnusbaum @bitwiseman
=> [JENKINS-63254][JENKINS-47101] Watch sensitive variables

Jenkinsfile
Like https://github.com/jenkinsci/file-parameters-plugin/pull/44. CC @olblak, @MarkEWaite, @timja, not sure who manages this sort of thing?
=> `maven-windows` agents seem broken

src/main/resources/org/jenkinsci/plugins/credentialsbinding/impl/CertificateMultiBinding/help.html, src/main/resources/org/jenkinsci/plugins/credentialsbinding/impl/FileBinding/help.html, src/main/resources/org/jenkinsci/plugins/credentialsbinding/impl/SSHUserPrivateKeyBinding/help.html, src/main/resources/org/jenkinsci/plugins/credentialsbinding/impl/StringBinding/help.html, src/main/resources/org/jenkinsci/plugins/credentialsbinding/impl/UsernamePasswordBinding/help.html, src/main/resources/org/jenkinsci/plugins/credentialsbinding/impl/UsernamePasswordMultiBinding/help.html, src/main/resources/org/jenkinsci/plugins/credentialsbinding/impl/ZipFileBinding/help.html
The changes introduce terminology updates to replace `master` by `controller` and remaining `slave` by `agent`.
This is lead by [JENKINS-65398](https://issues.jenkins.io/browse/JENKINS-65398).
=> [JENKINS-65398] Terminology update

src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStep.java, src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/SecretBuildWrapper.java, src/main/java/org/jenkinsci/plugins/credentialsbinding/masking/SecretPatterns.java
Also allows this new utility, and the existing `getAggregateSecretPattern`, to be consumed from other plugins: https://github.com/jenkinsci/credentials-binding-plugin/pull/59#discussion_r288735761
=> Introduced `MaskingOutputStream` to DRY between Pipeline & freestyle

src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStep.java, src/test/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStepTest.java
Should be the same effect as #141 but I think a little clearer to read. Also
* avoids wrapping a non-secret in `Secret`
* avoids storing secret variable names twice
=> [JENKINS-64361] Make fix for JENKINS-44860 apply to Pipeline step arguments as well (take II)

src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStep.java, src/test/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStepTest.java
See [JENKINS-64631](https://issues.jenkins.io/browse/JENKINS-64631).
#131 fixed [JENKINS-44860](https://issues.jenkins.io/browse/JENKINS-44860) by allowing usernames to remain unmasked in build logs, but it did not update the method introduced in #105 that Pipeline uses to know what environment variables contain secrets, so usernames were still being masked in Pipeline step arguments regardless of the value of `UsernameCredentials.isUsernameSecret`. This PR is a minor extension to #131 to address that issue.
=> [JENKINS-64361] Make fix for JENKINS-44860 apply to Pipeline step arguments as well

pom.xml, src/test/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStepTest.java
Tests https://github.com/jenkinsci/credentials-plugin/pull/293.
=> Integration test of `Credentials.forRun`

.github/CODEOWNERS, pom.xml, src/test/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStepTest.java
Like an idiot, in #179 I inadvertently disabled much of the interesting test coverage in this plugin, which was not noticed by reviewers because…I waited for months without review and gave up.
=> Restoring `BindingStepTest`

pom.xml, src/main/java/org/jenkinsci/plugins/credentialsbinding/masking/SecretPatterns.java, src/test/java/org/jenkinsci/plugins/credentialsbinding/masking/SecretPatternsTest.java
Cleans up after #239, especially relevant now given https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/323.
=> [SECURITY-3075] `getAggregateSecretPattern` to fail when run inside agent JVM

src/main/java/org/jenkinsci/plugins/credentialsbinding/masking/Base64SecretPatternFactory.java, src/test/java/org/jenkinsci/plugins/credentialsbinding/masking/Base64SecretPatternFactoryTest.java, src/test/java/org/jenkinsci/plugins/credentialsbinding/test/Base64PatternTest.java, src/test/java/org/jenkinsci/plugins/credentialsbinding/test/CredentialsTestUtil.java
There is no support for base64-encoded credentials, and it's not an encryption method and it can be easily decoded.
To prevent base64-encoded credentials from being exposed in build logs, I added a new SecretPatternFactory for it.
I wrote a test to ensure it was done properly on Windows and Unix-based systems but I also tested it locally with the following pipeline:
```
node {
withCredentials([usernamePassword(credentialsId: "CredID1", usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
sh '''
echo Base64 encoded password:
echo -n $PASSWORD | base64
echo "========================================"
curl -v https://$USERNAME:$PASSWORD@google.com
echo "========================================"
'''
}
}
```
<details>
<summary>Before:</summary>
</details>
<details> …
=> Add base64 masking

src/test/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStepTest.java
Otherwise can get PCT flakes such as
```
java.nio.file.NoSuchFileException: …/target/tmp/j h8642771068129316003/jobs/p/builds/1/atomic7832996773747571639.tmp
at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
at java.base/java.nio.file.Files.newByteChannel(Files.java:422)
at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
at java.base/java.nio.file.Files.newInputStream(Files.java:156)
at …
```
=> Ignore temporary files in `BindingStepTest.grep`

pom.xml, src/main/java/org/jenkinsci/plugins/credentialsbinding/BindingDescriptor.java, src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/ZipFileBinding.java, src/test/java/org/jenkinsci/plugins/credentialsbinding/impl/SSHUserPrivateKeyBindingTest.java
=> jep-227 downstream usage

pom.xml, src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/SSHUserPrivateKeyBinding.java
[Plugin pom 4.77](https://github.com/jenkinsci/plugin-pom/releases/tag/plugin-4.77) needs this change to resolve new spotbugs warnings that will be reported by spotbugs 4.8.3 and later.
Can skip the changelog, since this is not visible to users.
Confirmed that the spotbugs warnings are visible when using the 4.77-SNAPSHOT plugin pom before this change. With this change, the spotbugs warnings are no longer visible.
Confirmed that spotbugs is silent with plugin pom 4.77 after this change.
```[tasklist]
```
=> Suppress warnings for spotbugs 4.8.3

pom.xml, src/test/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStepTest.java
The `workflow-step-api` plugin changed the wording on the invalid context error. It has to be updated here as well.
cc @jglick 
Running the test with only the pom update and then updated the text string expectation. 
This is a follow of https://github.com/jenkinsci/workflow-step-api-plugin/pull/143 and coming from https://github.com/jenkinsci/bom/pull/2846
```[tasklist]
```
=> Fixes invalid context expectation in test

pom.xml, src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStep.java, src/test/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStepTest.java
Uses https://github.com/jenkinsci/workflow-step-api-plugin/pull/143. Amends #287.
=> Improved usage of `MissingContextVariableException`

src/main/java/org/jenkinsci/plugins/credentialsbinding/masking/Base64SecretPatternFactory.java, src/main/java/org/jenkinsci/plugins/credentialsbinding/masking/SecretPatterns.java, src/test/java/org/jenkinsci/plugins/credentialsbinding/masking/Base64SecretPatternFactoryTest.java
Amends #269. Keeps the integration test from #284 but reimplements the fix; I found that even input secrets of several characters could produce junk sequences in `Base64SecretPatternFactory`.
=> [JENKINS-72412] Overmasking when trivial “secrets” bound

src/main/java/org/jenkinsci/plugins/credentialsbinding/masking/Base64SecretPatternFactory.java, src/test/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStepTest.java, src/test/java/org/jenkinsci/plugins/credentialsbinding/masking/Base64SecretPatternFactoryTest.java
The fix makes sure that the Base64 secret patterns are not empty.
See https://issues.jenkins.io/browse/JENKINS-72412
The first of these commits include unit tests to demonstrate this issue.
```[tasklist]
```
=> Fix wrong masking of one-char-secrets in Jenkins output

src/test/java/org/jenkinsci/plugins/credentialsbinding/impl/CertificateMultiBindingTest.java
Adapt to https://github.com/jenkinsci/credentials-plugin/pull/540 by not using code about to be removed
` mvn clean test -Dtest=CertificateMultiBindingTest#basics`
=> do not rely on long deprecated FileOnMasterKeyStoreSource

src/test/java/org/jenkinsci/plugins/credentialsbinding/impl/CertificateMultiBindingTest.java
Adapt to jenkinsci/credentials-plugin#540
ammends #310 
ran `mvn verify` with the following change
```diff
diff --git a/pom.xml b/pom.xml
index 167d1e7..4eec89d 100644
--- a/pom.xml
+++ b/pom.xml
@@ -17,7 +17,7 @@
<url>https://github.com/jenkinsci/${project.artifactId}-plugin</url>
<properties>
<changelist>999999-SNAPSHOT</changelist>
-    <jenkins.version>2.414.3</jenkins.version>
+    <jenkins.version>2.426.3</jenkins.version>
<gitHubRepo>jenkinsci/${project.artifactId}-plugin</gitHubRepo>
</properties>
<licenses>
@@ -62,6 +62,7 @@
<dependency>
<groupId>org.jenkins-ci.plugins</groupId>
<artifactId>credentials</artifactId>
+      <version>1355.v46f52a_b_98d64</version>
</dependency>
<dependency>
<groupId>org.jenkins-ci.plugins</groupId>
```
=> Remove missed occurence of FileOnMasterKeyStoreSource

src/main/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStep.java, src/test/java/org/jenkinsci/plugins/credentialsbinding/impl/BindingStepTest.java
Supersedes https://github.com/jenkinsci/credentials-binding-plugin/pull/377.
The issue encountered in [JENKINS-75914](https://issues.jenkins.io/browse/JENKINS-75914) is due to the lack of handling for empty credentials. 
A check is performed for normal messages on the console log https://github.com/jenkinsci/credentials-binding-plugin/blob/baac667811a5f0121077979911c5853a8fb1ab12/src/main/java/org/jenkinsci/plugins/credentialsbinding/masking/SecretPatterns.java#L102, but not for exceptions.
I'm adding this check before changing the type of exception, to avoid throwing a `MaskedException` when there's nothing to mask.
I tested this change locally using the example provided in [JENKINS-75914](https://issues.jenkins.io/browse/JENKINS-75914) and added a test to cover this case. The test fails …
=> [JENKINS-75914] Do not mask empty secrets
